import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation,Link,Routes,Route,Navigate} from 'react-router-dom';
import {MessageSquare,LayoutDashboard,LogOut,PlusCircle,User,ShieldCheck,Menu, X, ArrowLeft, Send, CheckCircle2, Clock3} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar,CartesianGrid} from 'recharts';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
async function csrf(){const r=await fetch(`${API}/csrf`,{credentials:'include'});return (await r.json()).csrfToken}
async function api(path,options={}){
  const opts={credentials:'include',...options,headers:{...(options.headers||{})}};
  if(opts.method && opts.method!=='GET'){
    const token=await csrf(); opts.headers['x-csrf-token']=token;
  }
  if(opts.body && !(opts.body instanceof FormData)){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}
  const r=await fetch(API+path,opts); const data=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.message||'Request gagal'); return data;
}

function App(){
 const [user,setUser]=useState(null);
 useEffect(()=>{api('/auth/me').then(d=>setUser(d.user)).catch(()=>{})},[]);
 return <Routes>
  <Route path="/" element={<Landing user={user}/>}/>
  <Route path="/login" element={<Login onLogin={setUser}/>}/>
  <Route path="/register" element={<Register/>}/>
  <Route path="/forgot-password" element={<Forgot/>}/>
  <Route path="/mahasiswa/*" element={user?.role==='mahasiswa'?<StudentLayout user={user} setUser={setUser}/>:<Navigate to="/login"/>}/>
  <Route path="/admin/*" element={user&&['admin','super_admin'].includes(user.role)?<AdminLayout user={user} setUser={setUser}/>:<Navigate to="/login"/>}/>
  <Route path="*" element={<Navigate to="/"/>}/>
 </Routes>
}

function Landing({user}){
 return <div className="landing">
  <nav className="nav container"><Link to="/" className="brand"><span className="brand-mark">A</span> Aspirasi Fakultas</Link><div className="nav-actions">{user?<Link className="btn primary" to={user.role==='mahasiswa'?'/mahasiswa':'/admin'}>Dashboard</Link>:<><Link to="/login">Masuk</Link><Link className="btn primary" to="/register">Daftar</Link></>}</div></nav>
  <main className="hero container"><div className="hero-copy"><span className="eyebrow">PLATFORM ASPIRASI MAHASISWA</span><h1>Sampaikan aspirasi.<br/><em>Wujudkan perubahan.</em></h1><p>Salurkan saran, masukan, dan keluhan tentang lingkungan fakultas secara terstruktur. Pantau prosesnya sampai selesai.</p><div className="hero-buttons"><Link className="btn primary big" to={user?'/mahasiswa/new':'/register'}><PlusCircle size={19}/> Kirim Aspirasi</Link><a className="btn ghost big" href="#cara">Pelajari cara kerja</a></div></div><div className="hero-card"><MessageSquare size={38}/><h3>Suara kamu, didengar.</h3><p>Setiap aspirasi tercatat dan dapat dipantau statusnya.</p><div className="mini-status"><span className="dot"/> Aspirasi sedang diproses</div></div></main>
  <section id="cara" className="section container"><span className="eyebrow">CARA KERJA</span><h2>Sederhana dari awal sampai selesai.</h2><div className="steps"><Step n="01" t="Tulis aspirasi" d="Jelaskan masalah atau saran secara jelas dan lengkap."/><Step n="02" t="Ditinjau fakultas" d="Admin menerima, meninjau, dan memproses aspirasi."/><Step n="03" t="Pantau hasilnya" d="Lihat status dan tanggapan langsung dari dashboard." /></div></section>
 </div>
}
function Step({n,t,d}){return <div className="step"><b>{n}</b><h3>{t}</h3><p>{d}</p></div>}

function AuthShell({children,title,subtitle}){return <div className="auth"><div className="auth-brand"><Link to="/" className="brand"><span className="brand-mark">A</span> Aspirasi Fakultas</Link></div><div className="auth-card"><h1>{title}</h1><p>{subtitle}</p>{children}</div></div>}
function Login({onLogin}){const nav=useNavigate();const [f,setF]=useState({identifier:'',password:''});const [err,setErr]=useState('');
 const submit=async e=>{e.preventDefault();setErr('');try{const d=await api('/auth/login',{method:'POST',body:f});onLogin(d.user);nav(d.user.role==='mahasiswa'?'/mahasiswa':'/admin')}catch(e){setErr(e.message)}};
 return <AuthShell title="Selamat datang" subtitle="Masuk untuk mengelola aspirasi kamu."><form onSubmit={submit}>{err&&<Alert>{err}</Alert>}<Field label="NIM atau Email"><input value={f.identifier} onChange={e=>setF({...f,identifier:e.target.value})} required/></Field><Field label="Password"><input type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/></Field><div className="right"><Link to="/forgot-password">Lupa password?</Link></div><button className="btn primary full">Masuk</button></form><p className="auth-foot">Belum punya akun? <Link to="/register">Daftar sekarang</Link></p></AuthShell>}
function Register(){const nav=useNavigate();const [f,setF]=useState({nama:'',nim:'',email:'',program_studi:'',password:'',konfirmasi_password:''});const [err,setErr]=useState('');
 const submit=async e=>{e.preventDefault();try{await api('/auth/register',{method:'POST',body:f});nav('/login')}catch(e){setErr(e.message)}};
 return <AuthShell title="Buat akun mahasiswa" subtitle="Daftar untuk mulai menyampaikan aspirasi."><form onSubmit={submit}>{err&&<Alert>{err}</Alert>}<Field label="Nama lengkap"><input required value={f.nama} onChange={e=>setF({...f,nama:e.target.value})}/></Field><div className="grid2"><Field label="NIM"><input required value={f.nim} onChange={e=>setF({...f,nim:e.target.value})}/></Field><Field label="Program Studi"><input required value={f.program_studi} onChange={e=>setF({...f,program_studi:e.target.value})}/></Field></div><Field label="Email"><input type="email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></Field><div className="grid2"><Field label="Password"><input type="password" minLength="8" required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></Field><Field label="Konfirmasi"><input type="password" required value={f.konfirmasi_password} onChange={e=>setF({...f,konfirmasi_password:e.target.value})}/></Field></div><button className="btn primary full">Daftar</button></form><p className="auth-foot">Sudah punya akun? <Link to="/login">Masuk</Link></p></AuthShell>}
function Forgot(){const [email,setEmail]=useState('');const [msg,setMsg]=useState('');return <AuthShell title="Lupa password?" subtitle="Masukkan email akun kamu."><form onSubmit={async e=>{e.preventDefault();const d=await api('/auth/forgot-password',{method:'POST',body:{email}});setMsg(d.message)}}>{msg&&<Alert success>{msg}</Alert>}<Field label="Email"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><button className="btn primary full">Kirim instruksi</button></form><p className="auth-foot"><Link to="/login">← Kembali ke login</Link></p></AuthShell>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Alert({children,success}){return <div className={success?'alert success':'alert'}>{children}</div>}

function Shell({user,setUser,admin=false,children}){
 const [open,setOpen]=useState(false);const nav=useNavigate();
 const logout=async()=>{await api('/auth/logout',{method:'POST'});setUser(null);nav('/login')};
 return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="side-brand"><span className="brand-mark">A</span><b>Aspirasi</b></div><nav>{admin?<><SideLink to="/admin" icon={<LayoutDashboard size={18}/>} t="Dashboard"/><SideLink to="/admin/complaints" icon={<MessageSquare size={18}/>} t="Aspirasi Masuk"/></>:<><SideLink to="/mahasiswa" icon={<LayoutDashboard size={18}/>} t="Dashboard"/><SideLink to="/mahasiswa/new" icon={<PlusCircle size={18}/>} t="Kirim Aspirasi"/></>}</nav><button className="logout" onClick={logout}><LogOut size={18}/> Keluar</button></aside><div className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div/><div className="profile"><div className="avatar">{user.nama?.[0]}</div><span>{user.nama}</span></div></header><main className="content">{children}</main></div></div>
}
function SideLink({to,icon,t}){return <Link className="side-link" to={to}>{icon}<span>{t}</span></Link>}

function StudentLayout({user,setUser}){return <Shell user={user} setUser={setUser}><Routes><Route index element={<StudentHome/>}/><Route path="new" element={<NewComplaint/>}/><Route path="complaint/:id" element={<ComplaintDetail/>}/></Routes></Shell>}
function StudentHome(){const [items,setItems]=useState([]);useEffect(()=>{api('/complaints/mine').then(setItems)},[]);const count=s=>items.filter(x=>x.status===s).length;
 return <><PageHead eyebrow="DASHBOARD MAHASISWA" title="Halo, selamat datang 👋" desc="Pantau seluruh aspirasi yang pernah kamu sampaikan." action={<Link className="btn primary" to="/mahasiswa/new"><PlusCircle size={18}/> Kirim Aspirasi</Link>}/><div className="stat-grid"><Stat icon={<MessageSquare/>} n={items.length} t="Total Aspirasi"/><Stat icon={<Clock3/>} n={count('Diproses')} t="Diproses"/><Stat icon={<CheckCircle2/>} n={count('Selesai')} t="Selesai"/></div><section className="panel"><div className="panel-head"><div><h3>Riwayat Aspirasi</h3><p>Daftar pengajuan terbaru kamu.</p></div></div>{items.length?<div className="table-wrap"><table><thead><tr><th>Judul</th><th>Kategori</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><Link className="table-title" to={`/mahasiswa/complaint/${x.id}`}>{x.judul}</Link></td><td>{x.kategori}</td><td><Status s={x.status}/></td><td>{new Date(x.created_at).toLocaleDateString('id-ID')}</td></tr>)}</tbody></table></div>:<Empty/>}</section></>
}
function Stat({icon,n,t}){return <div className="stat"><div className="stat-icon">{icon}</div><div><strong>{n}</strong><span>{t}</span></div></div>}
function Status({s}){return <span className={`status status-${s.toLowerCase().replace('/','-')}`}>{s}</span>}
function PageHead({eyebrow,title,desc,action}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Empty(){return <div className="empty"><MessageSquare size={34}/><h3>Belum ada aspirasi</h3><p>Mulai sampaikan masukan kamu.</p></div>}

function NewComplaint(){const nav=useNavigate();const [cats,setCats]=useState([]);const [f,setF]=useState({judul:'',kategori_id:'',deskripsi:'',is_anonim:false});const [file,setFile]=useState(null);const [err,setErr]=useState('');
 useEffect(()=>{api('/categories').then(setCats)},[]);
 const submit=async e=>{e.preventDefault();setErr('');const fd=new FormData();Object.entries(f).forEach(([k,v])=>fd.append(k,v));if(file)fd.append('lampiran',file);try{await api('/complaints',{method:'POST',body:fd});nav('/mahasiswa')}catch(e){setErr(e.message)}};
 return <><PageHead eyebrow="PENGAJUAN" title="Kirim Aspirasi" desc="Ceritakan masalah, saran, atau masukan yang ingin kamu sampaikan."/><div className="panel form-panel"><Link className="back" to="/mahasiswa"><ArrowLeft size={17}/> Kembali</Link><form onSubmit={submit}>{err&&<Alert>{err}</Alert>}<Field label="Judul aspirasi"><input maxLength="200" required value={f.judul} onChange={e=>setF({...f,judul:e.target.value})}/></Field><Field label="Kategori"><select required value={f.kategori_id} onChange={e=>setF({...f,kategori_id:e.target.value})}><option value="">Pilih kategori</option>{cats.map(c=><option value={c.id} key={c.id}>{c.nama_kategori}</option>)}</select></Field><Field label="Deskripsi"><textarea rows="8" required value={f.deskripsi} onChange={e=>setF({...f,deskripsi:e.target.value})}/></Field><Field label="Lampiran (opsional)"><input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.docx" onChange={e=>setFile(e.target.files[0])}/><small>Maks. 5 MB. JPG, PNG, WEBP, PDF, DOCX.</small></Field><label className="check"><input type="checkbox" checked={f.is_anonim} onChange={e=>setF({...f,is_anonim:e.target.checked})}/><span><b>Kirim sebagai anonim</b><small>Nama tidak ditampilkan pada sisi mahasiswa. Identitas tetap tersimpan secara internal untuk akuntabilitas.</small></span></label><button className="btn primary"><Send size={17}/> Kirim Aspirasi</button></form></div></>
}

function ComplaintDetail(){const {id}=useParamsFix();const [item,setItem]=useState(null);useEffect(()=>{api(`/complaints/${id}`).then(setItem)},[id]);if(!item)return <div className="loading">Memuat...</div>;return <><PageHead eyebrow="DETAIL ASPIRASI" title={item.judul} desc={item.kategori}/><div className="detail-grid"><section className="panel"><Status s={item.status}/><h2>{item.judul}</h2><p className="detail-desc">{item.deskripsi}</p>{item.lampiran_url&&<a className="attachment" href={`http://localhost:5000${item.lampiran_url}`} target="_blank">Lihat lampiran</a>}</section><section className="panel"><h3>Perjalanan Aspirasi</h3><div className="timeline"><div><b>Dikirim</b><span>{new Date(item.created_at).toLocaleString('id-ID')}</span></div>{item.responses?.length?item.responses.map(r=><div key={r.id}><b>Tanggapan {r.admin_nama}</b><span>{new Date(r.created_at).toLocaleString('id-ID')}</span><p>{r.isi_tanggapan}</p></div>):<p>Belum ada tanggapan dari admin.</p>}</div></section></div></>}
function useParamsFix(){const loc=useLocation();return {id:loc.pathname.split('/').pop()};}

function AdminLayout({user,setUser}){return <Shell user={user} setUser={setUser} admin><Routes><Route index element={<AdminHome/>}/><Route path="complaints" element={<AdminComplaints/>}/><Route path="complaints/:id" element={<AdminDetail/>}/></Routes></Shell>}
function AdminHome(){const [s,setS]=useState(null);useEffect(()=>{api('/admin/stats').then(setS)},[]);if(!s)return <div className="loading">Memuat dashboard...</div>;return <><PageHead eyebrow="ADMINISTRATOR" title="Dashboard Fakultas" desc="Ringkasan pengelolaan aspirasi mahasiswa."/><div className="stat-grid five"><Stat n={s.totals.total||0} t="Total"/><Stat n={s.totals.baru||0} t="Baru"/><Stat n={s.totals.diproses||0} t="Diproses"/><Stat n={s.totals.ditanggapi||0} t="Ditanggapi"/><Stat n={s.totals.selesai||0} t="Selesai"/></div><div className="chart-grid"><section className="panel chart"><h3>Tren 30 Hari</h3><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="tanggal"/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="jumlah" strokeWidth={2}/></LineChart></ResponsiveContainer></div></section><section className="panel chart"><h3>Per Kategori</h3><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={s.categories}><XAxis dataKey="kategori" hide/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="jumlah"/></BarChart></ResponsiveContainer></div></section></div></>}
function AdminComplaints(){const [items,setItems]=useState([]);const [status,setStatus]=useState('');const load=()=>api('/admin/complaints'+(status?`?status=${encodeURIComponent(status)}`:'')).then(setItems);useEffect(load,[status]);return <><PageHead eyebrow="PENGELOLAAN" title="Aspirasi Masuk" desc="Tinjau dan kelola aspirasi mahasiswa."/><div className="panel"><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{['Baru','Diproses','Ditanggapi','Selesai','Ditolak'].map(s=><option key={s}>{s}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Judul</th><th>Pengirim</th><th>Kategori</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><Link className="table-title" to={`/admin/complaints/${x.id}`}>{x.judul}</Link></td><td>{x.is_anonim?'Anonim':x.nama}</td><td>{x.kategori}</td><td><Status s={x.status}/></td><td>{new Date(x.created_at).toLocaleDateString('id-ID')}</td></tr>)}</tbody></table></div></div></>}
function AdminDetail(){const {id}=useParamsFix();const [item,setItem]=useState(null);const [status,setStatus]=useState('');const [reply,setReply]=useState('');const [err,setErr]=useState('');const load=()=>api(`/complaints/${id}`).then(x=>{setItem(x);setStatus(x.status)});useEffect(load,[id]);if(!item)return <div className="loading">Memuat...</div>;
 const saveStatus=async()=>{try{await api(`/admin/complaints/${id}`,{method:'PATCH',body:{status}});load()}catch(e){setErr(e.message)}};const send=async()=>{try{await api(`/admin/complaints/${id}/responses`,{method:'POST',body:{isi_tanggapan:reply}});setReply('');load()}catch(e){setErr(e.message)}};
 return <><PageHead eyebrow="DETAIL ASPIRASI" title={item.judul} desc={`${item.kategori} • ${item.is_anonim?'Anonim':item.nama}`}/>{err&&<Alert>{err}</Alert>}<div className="detail-grid"><section className="panel"><h3>Isi Aspirasi</h3><p className="detail-desc">{item.deskripsi}</p>{item.lampiran_url&&<a className="attachment" href={`http://localhost:5000${item.lampiran_url}`} target="_blank">Lihat lampiran</a>}<hr/><h3>Status</h3><div className="inline-form"><select value={status} onChange={e=>setStatus(e.target.value)}>{['Baru','Diproses','Ditanggapi','Selesai','Ditolak'].map(s=><option key={s}>{s}</option>)}</select><button className="btn primary" onClick={saveStatus}>Simpan</button></div></section><section className="panel"><h3>Tanggapan Admin</h3><div className="responses">{item.responses?.map(r=><div className="response" key={r.id}><b>{r.admin_nama}</b><small>{new Date(r.created_at).toLocaleString('id-ID')}</small><p>{r.isi_tanggapan}</p></div>)}</div><textarea rows="6" placeholder="Tulis tanggapan..." value={reply} onChange={e=>setReply(e.target.value)}/><button className="btn primary" onClick={send}><Send size={17}/> Kirim Tanggapan</button></section></div></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
